version: '3.9'

networks:
  net:
    driver: bridge

services:
  redis:
    container_name: redis-cache
    image: redis:7.0.8
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ~/.redis/data:/data
    networks:
      - net
  
  commander:
    container_name: redis-ui
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: local:redis-cache:6379
      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - 8081:8081
    networks:
      - net
