version: '3.9'

networks:
  net-mongo:
    driver: bridge

services:
  mongodb:
    container_name: mongo
    image: mongo:4.4.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    networks:
      - net-mongo

  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongouser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopass
      ME_CONFIG_MONGODB_URL: mongodb://mongouser:mongopass@mongo:27017/
    networks:
      - net-mongo
